### PR TITLE
some minor optimisations and fixes

### PR DESCRIPTION
**Pull request by chicoxyzzy**
- caching
- fix global variable usage
- remove weird lines of code which do nothing

### CODE REVIEW

**Comment by daniel-lundin** [comment]
Thank you! Had a quick look and it seems like some bugs are introduced. The logo animation on the docs page doesn't work and the cards demo has some issues too.
Will go though it more thorough later..

**Comment by chicoxyzzy** [comment]
@daniel-lundin how can I reproduce this bug? I'll try to fix it

**Comment by chicoxyzzy** [comment]
also I can try to add some tests

**Comment by daniel-lundin** [comment]
@chicoxyzzy Run grunt, then copy the snabbt.min.js to docs/snabbt.min.js. If you open index.html and look at the header animation you will see that it stops after the letters has spun. 
I think it's you read _currentState in the Animation-constructor before it is set.

The cards demo seem to have from problem with reading the current transform from running animations. Might be the same cause.

**Comment by daniel-lundin** [comment]
Tests would be very welcome!

**Comment by daniel-lundin** [comment]
I merged it and fixed the issues.
Tests are still very welcome, btw :)

**Pull request closed without merging**
